// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xwfxqhwvcgjmvgwmpcij.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3ZnhxaHd2Y2dqbXZnd21wY2lqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5NjQ4OTksImV4cCI6MjA2NzU0MDg5OX0.qf1NPRVwCJY5OZueOF1EHp37lsPm-Rf6NdAnVPVlQt4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});